{
    'name': 'Asset Management',
    'version': '17.2',
    'category': 'Human Resources/Employees',
    'summary': 'This application streamlines the management of employee assets, allowing users to track, allocate, and maintain company assets efficiently. , Employee Asset Management, Asset Tracking Tool, Asset Allocation System, Company Asset Management, Employee Equipment Management, Asset Lifecycle Management, Asset Assignment for Employees, Asset Maintenance Tracker, Digital Asset Management, Asset Reporting System, Employee Asset Tracking, Asset Inventory Management, Asset Ownership Records, Equipment Allocation Software, Resource Management Tool, Asset Usage Monitoring, Asset Handover Process, Asset Return Management, Asset Compliance Tracker, Employee Resource Management',
    'author': 'INKERP',
    'website': 'https://www.inkerp.com/',
    'depends': ['hr', 'mail', 'pr_hr_account'],
    
    'data': [
        'security/ir.model.access.csv',
        'security/hr_security.xml',
        'data/ir_sequence.xml',
        'views/menu_items.xml',
        'views/asset_category_view.xml',
        'views/asset_detail_view.xml',
        'views/asset_location_view.xml',
        'views/asset_move_view.xml',
        'views/account_account.xml',
        'views/account_move.xml',
        'views/bank_payment.xml',
        'views/bank_receipt.xml',
        'views/cash_payment.xml',
        'views/cash_receipt.xml',
        'views/payment_receipt.xml',
        'views/transaction_payment.xml',
        'data/analytic_plan_data.xml',
    ],
    
    'images': ['static/description/banner.gif'],
    'license': "OPL-1",
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': '5.0',
    'currency': 'EUR',
}
